//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.18 at 11:08:49 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://soapwebservice.com/customer", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.soapwebservice.customer;
